### ISSUE TITLE
Crash after a certain amount of time

### ISSUE THREAD

**Issue by ps1x0** [blastehh/SourceQueryCacheMono#1]
Hello,

The process tends to crash after a certain amount of time (every couple of hours):

Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at QueryCache.MainClass.Main (System.String[] args) [0x00369] in <3df5c28086204bbd8a60093afafa9e72>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
  at QueryCache.MainClass.Main (System.String[] args) [0x00369] in <3df5c28086204bbd8a60093afafa9e72>:0

I'm using Debian 10.1 (kernel 4.19.0-6-amd64)
Mono JIT compiler version 6.4.0.198 (tarball Tue Sep 24 01:24:35 UTC 2019)

**Comment by blastehh** [comment]
Hi,

This project is no longer being developed, but there are a few forks that you could check out: https://github.com/blastehh/SourceQueryCacheMono/network/members
